# Generated by Django 5.2.11 on 2026-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_remove_servico_cliente_remove_servico_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('REC', 'Recebido'), ('PROD', 'Em Produção'), ('FIN', 'Finalizado'), ('ENT', 'Entregue'), ('CAN', 'Cancelado'), ('PRO', 'Provando')], default='REC', max_length=4),
        ),
    ]
